//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace System.Linq.Dynamic.BitWise.BWQS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBWQS", Namespace="http://tempuri.org/")]
    public partial class BWQS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback WhereOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderByOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderByDescendingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BWQS() {
            this.Url = global::System.Linq.Dynamic.BitWise.Properties.Settings.Default.BWQS_Client_System_Linq_Dynamic_BitWise_Service_BWQS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event QueryCompletedEventHandler QueryCompleted;
        
        /// <remarks/>
        public event WhereCompletedEventHandler WhereCompleted;
        
        /// <remarks/>
        public event OrderByCompletedEventHandler OrderByCompleted;
        
        /// <remarks/>
        public event OrderByDescendingCompletedEventHandler OrderByDescendingCompleted;
        
        /// <remarks/>
        public event GroupByCompletedEventHandler GroupByCompleted;
        
        /// <remarks/>
        public event GetGroupResultCompletedEventHandler GetGroupResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/Initialize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Initialize([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string packedAssemblyBuffer, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string className, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string packedDataSource) {
            this.Invoke("Initialize", new object[] {
                        packedAssemblyBuffer,
                        className,
                        packedDataSource});
        }
        
        /// <remarks/>
        public void InitializeAsync(string packedAssemblyBuffer, string className, string packedDataSource) {
            this.InitializeAsync(packedAssemblyBuffer, className, packedDataSource, null);
        }
        
        /// <remarks/>
        public void InitializeAsync(string packedAssemblyBuffer, string className, string packedDataSource, object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[] {
                        packedAssemblyBuffer,
                        className,
                        packedDataSource}, this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Query([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bwqExpr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialType) {
            object[] results = this.Invoke("Query", new object[] {
                        bwqExpr,
                        serialType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAsync(string bwqExpr, string serialType) {
            this.QueryAsync(bwqExpr, serialType, null);
        }
        
        /// <remarks/>
        public void QueryAsync(string bwqExpr, string serialType, object userState) {
            if ((this.QueryOperationCompleted == null)) {
                this.QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOperationCompleted);
            }
            this.InvokeAsync("Query", new object[] {
                        bwqExpr,
                        serialType}, this.QueryOperationCompleted, userState);
        }
        
        private void OnQueryOperationCompleted(object arg) {
            if ((this.QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCompleted(this, new QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/Where", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Where([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bwqExpr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialType) {
            object[] results = this.Invoke("Where", new object[] {
                        bwqExpr,
                        serialType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhereAsync(string bwqExpr, string serialType) {
            this.WhereAsync(bwqExpr, serialType, null);
        }
        
        /// <remarks/>
        public void WhereAsync(string bwqExpr, string serialType, object userState) {
            if ((this.WhereOperationCompleted == null)) {
                this.WhereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhereOperationCompleted);
            }
            this.InvokeAsync("Where", new object[] {
                        bwqExpr,
                        serialType}, this.WhereOperationCompleted, userState);
        }
        
        private void OnWhereOperationCompleted(object arg) {
            if ((this.WhereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhereCompleted(this, new WhereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/OrderBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderBy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bwqExpr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialType) {
            object[] results = this.Invoke("OrderBy", new object[] {
                        bwqExpr,
                        serialType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderByAsync(string bwqExpr, string serialType) {
            this.OrderByAsync(bwqExpr, serialType, null);
        }
        
        /// <remarks/>
        public void OrderByAsync(string bwqExpr, string serialType, object userState) {
            if ((this.OrderByOperationCompleted == null)) {
                this.OrderByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderByOperationCompleted);
            }
            this.InvokeAsync("OrderBy", new object[] {
                        bwqExpr,
                        serialType}, this.OrderByOperationCompleted, userState);
        }
        
        private void OnOrderByOperationCompleted(object arg) {
            if ((this.OrderByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderByCompleted(this, new OrderByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/OrderByDescending", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderByDescending([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bwqExpr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serialType) {
            object[] results = this.Invoke("OrderByDescending", new object[] {
                        bwqExpr,
                        serialType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderByDescendingAsync(string bwqExpr, string serialType) {
            this.OrderByDescendingAsync(bwqExpr, serialType, null);
        }
        
        /// <remarks/>
        public void OrderByDescendingAsync(string bwqExpr, string serialType, object userState) {
            if ((this.OrderByDescendingOperationCompleted == null)) {
                this.OrderByDescendingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderByDescendingOperationCompleted);
            }
            this.InvokeAsync("OrderByDescending", new object[] {
                        bwqExpr,
                        serialType}, this.OrderByDescendingOperationCompleted, userState);
        }
        
        private void OnOrderByDescendingOperationCompleted(object arg) {
            if ((this.OrderByDescendingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderByDescendingCompleted(this, new OrderByDescendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/GroupBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GroupBy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string grpExpr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _byExpr) {
            object[] results = this.Invoke("GroupBy", new object[] {
                        grpExpr,
                        _byExpr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GroupByAsync(string grpExpr, string _byExpr) {
            this.GroupByAsync(grpExpr, _byExpr, null);
        }
        
        /// <remarks/>
        public void GroupByAsync(string grpExpr, string _byExpr, object userState) {
            if ((this.GroupByOperationCompleted == null)) {
                this.GroupByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupByOperationCompleted);
            }
            this.InvokeAsync("GroupBy", new object[] {
                        grpExpr,
                        _byExpr}, this.GroupByOperationCompleted, userState);
        }
        
        private void OnGroupByOperationCompleted(object arg) {
            if ((this.GroupByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupByCompleted(this, new GroupByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBWQS/GetGroupResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GroupResult GetGroupResult() {
            object[] results = this.Invoke("GetGroupResult", new object[0]);
            return ((GroupResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupResultAsync() {
            this.GetGroupResultAsync(null);
        }
        
        /// <remarks/>
        public void GetGroupResultAsync(object userState) {
            if ((this.GetGroupResultOperationCompleted == null)) {
                this.GetGroupResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupResultOperationCompleted);
            }
            this.InvokeAsync("GetGroupResult", new object[0], this.GetGroupResultOperationCompleted, userState);
        }
        
        private void OnGetGroupResultOperationCompleted(object arg) {
            if ((this.GetGroupResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupResultCompleted(this, new GetGroupResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Linq.Dynamic.BitWise.Service")]
    public partial class GroupResult {
        
        private object keyField;
        
        private object valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InitializeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryCompletedEventHandler(object sender, QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WhereCompletedEventHandler(object sender, WhereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OrderByCompletedEventHandler(object sender, OrderByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OrderByDescendingCompletedEventHandler(object sender, OrderByDescendingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderByDescendingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderByDescendingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GroupByCompletedEventHandler(object sender, GroupByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGroupResultCompletedEventHandler(object sender, GetGroupResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591